services:
  frontend:
    build:
      context: ../.
      dockerfile: docker/DockerfileDev
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
    volumes:
      - ../.:${WORK_DIR}
    ports:
      - "4455:4200"
    working_dir: ${WORK_DIR}
    command: "/bin/bash docker/setup.sh"
    develop:
      watch:
        - path: ../src/
          target: /app/src/
          action: sync